### ISSUE TITLE
Can you provide more model files

### ISSUE THREAD

**Issue by pang-yi-jie** [jinfagang/nosmpl#11]
Can you provide links to all model files. Some demo files cannot function properly due to missing corresponding models, such as SMPLH_ Sim_ W_ Orien, but without smplh_ sim. Can you provide a link to the smplh_ sim file , PKL and npy files that cannot be found. Also, may I ask what the input format for orien is. Thank you for your reply

**Comment by lucasjinreal** [comment]
Hi, I don't have any license permission to provide any pkl or npy files of smpl, you can use ONNX model directly.

**Comment by pang-yi-jie** [comment]
Thank you for your reply. I can download the two onnx files you provided, but I can't download 'smplh_ sim. onnx 'file,。 can you also provide What is the data format of the global_orient
