### ISSUE TITLE
Rendering/Plotting speed

### ISSUE THREAD

**Issue by yufu-liu** [jinfagang/nosmpl#12]
Hi, I have used this tool for a month, and my recent goal is to have a real-time demo.

My computer's CPU is i7-11 and GPU is RTX 3070. In real-time situation, plotting time of each frame is around 0.02 seconds. 

Do you have any suggestion for accelerate the tool to decrease plotting time?

**Comment by lucasjinreal** [comment]
You can try run on GPU, it should be faster, and possibly even more faster then vanilla origin pytorch version.

**Comment by yufu-liu** [comment]
> You can try run on GPU, it should be faster, and possibly even more faster then vanilla origin pytorch version.

Hi, thanks for your fast reply!
Do you have an example using GPU to run?
I cannot find a related document on Open3D'website.

Is it as simple as Torch by setting my data from input.cpu() to input.cuda()?
Or how can I let Open3D know I want to use GPU to plot instead of CPU?

**Comment by lucasjinreal** [comment]
Note open3d is a visualize lib, onnx is a compute neural model format.

**Comment by yufu-liu** [comment]
Thanks for your hint.
I understand onnx is a model, so using SMPL.onnx for inference via GPU should be faster.
On the other hand, how do you know Open3D use CPU or GPU to plot the mesh after gaining onnx output?

**Comment by yufu-liu** [comment]
> Note open3d is a visualize lib, onnx is a compute neural model format.

Hi, Lucas

I found you have developed another tool alfred-py. Do you think it is possible to be faster when using it to plot **skeleton/keypoints of body** instead of plotting a **mesh** via nosmpl?
(After I tried SMPL.onnx, the speed didn't become faster...)
