### ISSUE TITLE
404 not found about https://star.is.tue.mpg.de/downloads

### ISSUE THREAD

**Issue by liuweixue001** [jinfagang/nosmpl#2]

**Comment by lucasjinreal** [comment]
You can search STAR, this repo mean to **not** using any SMPL model, I exported them to onnx

**Comment by lucasjinreal** [comment]
https://star.is.tue.mpg.de/

**Comment by wang-zm18** [comment]
Where to download SMPL.onnx and SMPLH.onnx?

**Comment by lucasjinreal** [comment]
It was in release. SMPL should export by users ownself.

**Comment by wang-zm18** [comment]
![image](https://user-images.githubusercontent.com/47704679/222136531-ef4fc51e-0789-452c-91dd-908e8f0801bf.png)
Could you please show me where to download the SMPLH.onnx?

**Comment by wang-zm18** [comment]
Hello, could you please show me how to export SMPLH.onnx?

**Comment by wang-zm18** [comment]
And where is the link of Wechat group and  QQ ?
