### ISSUE TITLE
No module named 'nosmpl.vis'

### ISSUE THREAD

**Issue by FANzhaoxin666** [jinfagang/nosmpl#3]
How to xolve this issue?

**Comment by lucasjinreal** [comment]
@FANzhaoxin666 hello! thank u for using nosmpl, can u tell me how did using nosmpl and how to get into this import error?

```
pip install -U nosmpl
```

might be help.

**Comment by SMY19999** [comment]
I meet this problem too. 
The nosmpl/vis/vis_o3d.py is exactly exist. But just cannot be imported.

**Comment by lucasjinreal** [comment]
@xiaoyang-RL9 Which code using? I can import vis . If it can not, try install using source code, it should be ok.

**Comment by SMY19999** [comment]
I just install by pip install nosmpl , it shows the version is 0.1.0. Now, I use trimesh to visualize the result.

**Comment by SMY19999** [comment]
by the way, the example code you show in ZhiHu and CSDN has a little error with the nosmpl=0.1.0.
In see.run(), it requires another input "global_orient": [ ].
For smpl.onnx, global_orient.shape = 1,1,3  like [[[1,0,1]]] ; for smplh.onnx global_orient.shape = 1,3  like [[1,1,1]].

**Comment by lucasjinreal** [comment]
@xiaoyang-RL9 it looks like you are using an old version, latest is 0.1.4

Please take a look at README, nosmpl provide a wrapper you can use out-of-box.

**Comment by SMY19999** [comment]
Thanks a lot. Due to the mirror source doesn't update in time. Just pip install directly and I get the latest version.
