### ISSUE TITLE
About the parameter 'global_orient' and 'R_along_aixs'

### ISSUE THREAD

**Issue by SMY19999** [jinfagang/nosmpl#4]
I have checked that the parameter of 'trans' and 'R_along_aixs' are operations applied on the output mesh, which is a rigid transformation according to the world center (0,0,0). And the 'global_orient' is the pose of root_joint of SMPL. 
In my opinion, 'trans' and 'global_orient' represent the rigid transformation of SMPL's root joint.
So, Q1: **what's the difference between 'R_along_aixs' and 'global_orient'?**
Q2: I have tested the sees.run in SMPL, and the shape of  'global_orient' is 1,1,3 like [ [ [ np.pi, 0, 0] ] ] which confused me a lot.
Looking forward to your reply.

**Comment by lucasjinreal** [comment]
@xiaoyang-RL9 Hello!

1. R_along_axis is for users to quickly customize mesh orientation in open3d, if you are not set this, it was just using global_orient, but actually, most of the time, open3d are not same direction as your mesh, that is for this purpose;
2. global_orient is your model output, it should be in rotvec format same as body. they are not same thing.

In short, R_along_axis mainly for post customization, Make users have largest flexiability to adjust the mesh orientation, nerverthless the model outputs.

**Comment by SMY19999** [comment]
> 

Thanks a lot! That's a considerate design！

**Comment by mayank64ce** [comment]
I am trying to rotate an SMPL pose sequence and figured out 'global_orient' could do it. but I dont exactly understand how ?
