### ISSUE TITLE
name 'os' is not defined

### ISSUE THREAD

**Issue by Bill-WangJiLong** [jinfagang/nosmpl#6]
Traceback (most recent call last):
  File "npzkook.py", line 20, in <module>
    smpl = SMPLOnnxRuntime()
  File "/usr/local/lib/python3.8/dist-packages/nosmpl/smpl_onnx.py", line 19, in __init__
    preset_file_path = os.path.join(
NameError: name 'os' is not defined

**Comment by Bill-WangJiLong** [comment]
nosmpl == 0.1.4

**Comment by lucasjinreal** [comment]
install onnxruntime.

**Comment by lucasjinreal** [comment]
<img width="349" alt="image" src="https://user-images.githubusercontent.com/21303438/235387442-bde90ddc-1050-46d9-85ad-b53513f6df66.png">

pip install alfred-py as well.

**Comment by kexul** [comment]
In my case, it turns out that I dont have `rich` installed. 
Not sure why rich is not installed as dependency. 

@lucasjinreal  can we remove the `try...expect` so that the unsatisfied requirement is exposed?

**Comment by lucasjinreal** [comment]
PR are very welcomed. I am not not doing SMPL related work for now, but will very happy to help your guys using `nosmpl` .

Any enhancement are very welcomed!
